blueprint:
  name: Awtrix – Wyświetlanie danych z encji (sensor/weather)
  description: >
    Publikuje wartość encji (lub atrybutu temperature dla weather) do AWtrix przez MQTT
    z konfigurowalną ikoną, liczbą powtórzeń, czcionką i opcjami tekstu (wielkie litery / brak przewijania).
  domain: automation
  input:
    sensor_entity:
      name: Encja źródłowa (entity_id)
      description: Wpisz entity_id encji (np. sensor.lazienka_temperature lub weather.forecast_dom).
                   Możesz skorzystać z autocomplete w UI przy tworzeniu automatyzacji.
      selector:
        text:
          multiline: false
    awtrix_topic:
      name: Temat MQTT
      description: Temat MQTT dla Twojego urządzenia AWtrix (np. awtrix_664dc4/custom/sypialnia)
      selector:
        text:
          multiline: false
    icon_id:
      name: ID ikony
      default: 1447
      selector:
        number:
          min: 0
          max: 99999
    push_icon:
      name: pushIcon
      default: 2
      selector:
        number:
          min: 0
          max: 2
          mode: slider
    repeat_count:
      name: Liczba powtórzeń
      default: 1
      selector:
        number:
          min: 1
          max: 10
    uppercase:
      name: Wielkie litery
      default: true
      selector:
        boolean: {}
    no_scroll:
      name: Bez przewijania
      default: false
      selector:
        boolean: {}
    font_id:
      name: ID czcionki
      default: 0
      selector:
        number:
          min: 0
          max: 10

variables:
  sensor_entity: !input sensor_entity
  awtrix_topic: !input awtrix_topic
  icon_id: !input icon_id
  push_icon: !input push_icon
  repeat_count: !input repeat_count
  uppercase: !input uppercase
  no_scroll: !input no_scroll
  font_id: !input font_id

trigger:
  - platform: state
    entity_id: !input sensor_entity

action:
  - service: mqtt.publish
    data:
      topic: !input awtrix_topic
      retain: false
      payload: >
        {
          "text": "{% set raw = state_attr(sensor_entity, 'temperature') if state_attr(sensor_entity, 'temperature') is not none else states(sensor_entity) %}{% if raw in ['unknown','unavailable','', none] %}N/A{% else %}{{ (raw | float | round(1)) }}°C{% endif %}",
          "icon": "{{ icon_id }}",
          "pushIcon": {{ push_icon }},
          "repeat": {{ repeat_count }},
          "noScroll": {{ 'true' if no_scroll else 'false' }},
          "uppercase": {{ 'true' if uppercase else 'false' }},
          "font": {{ font_id }}
        }

mode: restart
